### PR TITLE
fixed another small bug

### LINKED ISSUE #16: Output bug
I was comparing the output of gosecretsdump to secretsdump and found a small output issue:
https://github.com/SecureAuthCorp/impacket/blob/a16198c3312d8cfe25b329907b16463ea3143519/impacket/examples/secretsdump.py#L2123

Compared to this:
https://github.com/C-Sto/gosecretsdump/blob/f7230a2bec7baffa4c2029daaf31ae40e18eab30/pkg/ditreader/records.go#L87

`nsAMAccountName` should be used instead of the two parts of the `nuserPrincipalName`

### PR DESCRIPTION
**Pull request by yoav-orca**
Fixes #16

### CODE REVIEW

**Comment by C-Sto** [comment]
I like it - I have previously been verifying impacket output using a small reference .dit hosted on https://github.com/c-sto/ntds_reference, which is checked during testing with this function https://github.com/C-Sto/gosecretsdump/blob/master/test/acuracy_test.go#L29-L67 - if you can contribute another reference .dit with the expected output, I can add that to the test suite so that we can be more sure regressions aren't encountered. 

Keen to stay compliant with impacket output by default if possible, so thank you for the contributions, very much appreciated.

**Comment by yoav-orca** [comment]
@C-Sto I would love to share them but they are part of an engagement so they are private :|
I have a utility that currently runs both impacket and gosecertsdump and reports on diffs, so I'm sharing findings here

**Comment by C-Sto** [comment]
Totally understand - lab environment .dit files can be hard to manufacture to hold the right data too, so there is always a lot of effort in creating those test cases. 

I'll see if I can add samples for the issues you identified; I'll need to add older .dit examples for different functional levels anyway.

**Comment by p-b--** [comment]
Just as an update -- I used this patch to extract a ntds.dit file -- it worked as expected. It used the samaccountname instead of UPN.

**Pull request merged**
